version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      tailwind:
        patterns:
          - "tailwindcss"
          - "autoprefixer"
          - "postcss"
          - "@astrojs/tailwind"
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "@codecov/astro-plugin"
      preact:
        patterns:
          - "preact"
          - "lucide-preact"
          - "@testing-library/preact"
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"